In [62]:
from sklearn.cluster import KMeans
from sklearn.metrics import normalized_mutual_info_score
import pandas as pd

The assumption is that, by clustering both the hyperspectral and the fractional cover measurements, the clusterings will be similar, i.e. a sample which is close to other samples in terms of hyperspectral measurements would also be close from the point of view of fractional cover. If this is not true, that it is likely that there is no correlation between those measurements. The second stronger assumption is that each cluster will correspond to measurements from just one plot. If this is not true, then it is likely that the measurements are completely independent of the plot they have been taken in, so there is probably no correlation to other measurements taken from the same plot.

In [63]:
features_pca = pd.read_csv("datasets/10features_pca.csv").to_numpy()
fractional_cover = pd.read_csv("datasets/complete_fc.csv").to_numpy()

In [64]:
features_pca

array([[ -2.78563161, -15.29500909,   9.61307589, ...,   1.88190458,
          0.63761465,  -0.06718317],
       [-29.89724085, -17.97538308,  23.39548645, ...,   3.68282091,
          3.03555686,  -0.95001886],
       [  5.94883324,  -5.42694336,   4.00566377, ...,   4.0219997 ,
          1.92231025,   0.85569335],
       ...,
       [ -5.85832894, -12.32179918, -11.16971251, ...,   1.90179165,
          0.89950262,   0.07780176],
       [ 24.99322276,  10.97564101, -10.04499787, ...,   4.05120409,
          0.69606782,  -0.36735629],
       [-11.09939396, -18.23812107, -14.25655914, ...,   2.22645763,
          0.72874516,   0.20453164]], shape=(869, 10))

In [65]:
fractional_cover

array([[0.41 , 0.04 , 0.   , 0.55 , 0.   ],
       [0.475, 0.03 , 0.   , 0.495, 0.   ],
       [0.54 , 0.02 , 0.   , 0.44 , 0.   ],
       ...,
       [0.64 , 0.   , 0.   , 0.36 , 0.   ],
       [0.64 , 0.   , 0.   , 0.36 , 0.   ],
       [0.64 , 0.   , 0.   , 0.36 , 0.   ]], shape=(869, 5))

In [66]:
kmeans_features_pca = KMeans(n_clusters=58).fit(features_pca)
features_pca_labels = kmeans_features_pca.labels_
kmeans_fractional_cover = KMeans(n_clusters=58).fit(fractional_cover)
fractional_cover_labels = kmeans_fractional_cover.labels_

In [67]:
features_pca_labels

array([48, 41,  3, 18,  9, 38, 40, 13, 11, 38,  9, 26,  9, 41, 31, 57, 17,
        5, 54, 54, 54, 37, 35, 35,  0, 54,  7,  7, 54, 54, 19, 19, 19, 57,
       25, 57, 19, 57, 57, 14, 19,  7, 57, 19, 24, 24, 24, 13, 13, 24, 42,
        9, 24, 26, 17,  9, 34, 24, 57, 13,  0, 37,  5, 16, 37,  0, 18, 16,
        3,  0,  0, 55, 56, 56, 37,  9,  3, 48, 46,  7, 34,  3,  3, 34, 17,
       17,  3, 34, 23, 32, 18, 18, 18, 16, 18,  8, 18,  2, 56, 56, 20,  8,
       56,  8, 33, 41,  2,  2, 41,  9, 48, 53, 17,  3, 48,  8, 26, 48, 38,
       48,  0, 16, 37, 16, 16, 37,  0,  0, 16, 18, 56, 18,  0, 16, 42, 48,
       46, 41, 46, 48, 18, 42, 38,  3,  3, 46, 34, 34, 34, 34, 40, 38, 40,
       38,  9,  1,  1,  1, 17,  9,  3, 16, 16, 38, 40,  3, 42,  0,  0,  0,
       42, 24,  3,  0, 17, 42,  0, 50, 34,  2,  8,  2, 18, 56, 18,  8, 16,
       41, 18,  8, 48, 41, 41,  8, 18, 26,  1, 40, 26,  2,  2,  2,  2, 48,
        8,  8,  8,  8, 18, 56, 56,  0, 56, 10, 10,  8, 10, 10, 10, 56, 18,
        1, 10,  8, 10, 10

In [68]:
fractional_cover_labels

array([40, 45, 26, 12, 37, 26, 45, 18, 42, 42, 42, 42, 42, 42, 42, 45, 26,
       12, 37, 52, 37, 12, 26, 45, 26, 12, 12, 37, 37, 37, 45, 45, 45, 45,
       26, 26, 12, 37, 52, 52, 37, 37, 12, 12, 12, 26, 26, 26, 26, 26, 26,
       45, 45, 45, 45, 45, 45, 45, 45, 45, 34, 34, 46, 46, 46, 34, 34, 28,
       56, 28, 34, 46, 36, 36, 36, 55, 55, 55, 55,  9,  9, 41, 41, 41, 41,
       41,  9,  9,  9,  9, 16,  6, 14, 50, 30, 30, 30, 30, 30, 52, 52,  1,
        1,  1,  1,  7,  7,  7, 49, 49, 49, 35, 35, 35, 35, 35,  7, 42, 42,
       42,  1, 52, 52, 52, 52, 37, 12, 26, 45, 26, 38, 23, 33, 33, 33,  7,
        7, 15, 15, 55, 15, 15,  7, 42, 18, 40, 10, 39, 39, 39, 44, 57, 25,
        2, 53, 53, 25, 48, 48, 47, 32,  6, 14, 14, 32,  6, 14, 50, 36,  4,
       30, 52, 37, 52, 30,  4, 36, 36, 36,  1, 33, 33,  6,  6, 39, 39, 38,
       10, 10, 40, 40, 40, 40, 40, 23, 38, 10, 40, 31, 31, 31, 48, 48, 47,
       39,  1,  4,  4,  4,  4,  4, 36, 36, 36, 36,  4,  4,  4, 52, 26, 45,
       42, 42, 42,  4,  1

Check similarity of clusterings.

In [69]:
normalized_mutual_info_score(features_pca_labels, fractional_cover_labels)

np.float64(0.42865353915861565)

The NMI score indicates a moderate to low level of similarity, so it is likely that the hyperspectral and the fractional cover measurements are modelled by very different distributions, which would make it difficult to predict one from the other. The assumption that one cluster will correspond to one plot was also incorrect, though we do observe some tendencies for neighboring locations to be clustered together.