In [124]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score

Sklearn train and test loaders

In [125]:
fractional_cover = pd.read_csv("datasets/fractional_cover.csv")
fractional_cover["tree_type"] = fractional_cover["plot_ID"].apply(lambda x: ''.join([char for char in x.split("_")[1] if char.isalpha()]))

X = pd.read_csv("datasets/1000_wavelength_10features_pca.csv").to_numpy()
y_intermediate_points = pd.read_csv("datasets/complete_fc.csv")
y_intermediate_points = y_intermediate_points[["vasc", "nonvasc", "lichen", "intactlitt", "decomplitt"]].to_numpy() * 100
y_plot_ids = fractional_cover["plot_ID"].to_numpy().repeat(15)
y_plot_ids = np.delete(y_plot_ids, np.where(y_plot_ids == "HY_PINE5")[0][0])
y_tree_types = fractional_cover["tree_type"].to_numpy().repeat(15)
y_tree_types = np.delete(y_tree_types, np.where(y_tree_types == "PINE")[0][0])

Predict using SVM.

In [126]:
# SVM code here
clf = SVC(kernel='linear')
X_train, X_test, y_train, y_test = train_test_split(X, y_plot_ids, test_size=0.2, random_state=42)
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.6149


In [127]:
clf = SVC(kernel='linear')
X_train, X_test, y_train, y_test = train_test_split(X, y_tree_types, test_size=0.2, random_state=42)
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.6954


Predict fractional cover measurements at individual locations using MLP.

In [128]:
mlp = MLPRegressor(hidden_layer_sizes=(100,), activation="tanh", solver="adam", batch_size=256, learning_rate="constant", learning_rate_init=0.001, max_iter=10000)

X_train, X_test, y_train, y_test = train_test_split(X, y_intermediate_points, test_size=0.1)

mlp.fit(X_train, y_train)
targets = mlp.predict(X_test)

print(f"Errors: {np.abs(np.round(targets - y_test, decimals=1))}")
print(f"MSE loss: {mean_squared_error(y_test, targets)}")
print(f"MAE loss: {mean_absolute_error(y_test, targets)}")

Errors: [[10.6 13.4  2.2 16.1  1.5]
 [25.4 28.8  0.5  3.7  5. ]
 [18.2 24.5  0.   1.8  0. ]
 [13.8  3.2  0.4  0.2  5.7]
 [ 0.8  3.9  0.5  0.6  0.1]
 [21.5 14.4  0.1  1.8  0.3]
 [14.1  3.3  0.1  7.7  2.7]
 [ 3.5  0.2  0.1  6.9  1.2]
 [ 5.7 12.3  0.6 12.1  0.7]
 [11.6 13.8  0.8  3.   0.5]
 [33.8 14.5  0.1 13.   0.9]
 [ 3.5  0.5  0.4  4.1  1. ]
 [18.7 15.1  0.1  0.8  0.8]
 [10.7 10.7  0.2  4.2  7.6]
 [ 3.1 10.9  0.2 11.2  0.8]
 [ 6.7  0.8  0.2 10.6 21. ]
 [ 7.8  6.7  0.9 22.3  7.3]
 [31.5 15.1  0.2 13.2  1.2]
 [19.   1.1  0.8 28.   9.4]
 [ 6.1  4.6  0.3 11.2  1.4]
 [24.4  6.8  0.1 28.6  0.8]
 [ 0.1  0.7  0.3  6.5  1.3]
 [ 3.1  0.2  0.2  5.5  1.7]
 [ 9.3  7.   0.1  3.4  0.2]
 [26.8 22.1  0.2  9.7  0.1]
 [32.8 37.7  2.   8.7  3.2]
 [12.1  9.4  0.4  1.8  0.9]
 [10.1  0.4  0.4  4.1  0.1]
 [ 6.3  1.1  0.1  1.7  8.4]
 [29.5 13.4  0.5  7.3  0.3]
 [ 0.1  7.6  0.3  3.4  1.4]
 [12.5  3.   0.2  5.  20.1]
 [13.9 14.2  0.5  6.5  0.7]
 [57.2  9.1  0.  60.9  0.3]
 [ 5.6  7.2  0.2  4.2  2. ]
 [17.7  0.8 

Predict plots using MLP.

In [129]:
mlp = MLPClassifier(hidden_layer_sizes=(100,), activation="tanh", solver="adam", batch_size=256, learning_rate="constant", learning_rate_init=0.001, max_iter=10000)

X_train, X_test, y_train, y_test = train_test_split(X, y_plot_ids, test_size=0.1)

mlp.fit(X_train, y_train)
targets = mlp.predict(X_test)

print(f"Accuracy of predictions: {accuracy_score(y_test, targets)}")

Accuracy of predictions: 0.6551724137931034


Predict tree types using MLP.

In [130]:
mlp = MLPClassifier(hidden_layer_sizes=(100,), activation="tanh", solver="adam", batch_size=256, learning_rate="constant", learning_rate_init=0.001, max_iter=10000)

X_train, X_test, y_train, y_test = train_test_split(X, y_tree_types, test_size=0.1)

mlp.fit(X_train, y_train)
targets = mlp.predict(X_test)

print(f"Accuracy of predictions: {accuracy_score(y_test, targets)}")


Accuracy of predictions: 0.8275862068965517
